# Configuration de validation des tokens Keycloak JWT en production
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/incidentflow-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://incidentflow-keycloak-v2:8080/realms/incidentflow-realm/protocol/openid-connect/certs
